[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myProject.myProject.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
